### ISSUE TITLE
Jetson MemoryTracker no memory data collected on jetson.

### ISSUE THREAD

**Issue by FlagZhao** [NVIDIA/compute-sanitizer-samples#15]
Hi,

I tested the MemoryTracker  with cuda11.8 on both A5000 server(x86-64 ubuntu20.04) and nvorin(jetson aarch64 20.04). The memory tracker seems did not collect any information on orin. I have already copied the fatbin into the same dir as #9 mentioned. 

The command is:
LD_PRELOAD=/home/yzhao62/sanitizer_samples/temp/compute-sanitizer-samples/MemoryTracker/libMemoryTracker.so:/usr/local/cuda-11.8/compute-sanitizer/libsanitizer-public.so ./matrixMul

The output of matrixMul on orin like blow:
[Matrix Multiply Using CUDA] - Starting...
GPU Device 0: "Ampere" with compute capability 8.7

MatrixA(320,320), MatrixB(640,320)
successfully entered here
Computing result using CUDA Kernel...
done
Kernel Launch: _Z13MatrixMulCUDAILi32EEvPfS0_S0_ii
  Memory accesses: 0
Performance= 145.29 GFlop/s, Time= 0.902 msec, Size= 131072000 Ops, WorkgroupSize= 1024 threads/block
Kernel Launch: _Z13MatrixMulCUDAILi32EEvPfS0_S0_ii
  Memory accesses: 0
Kernel Launch: _Z13MatrixMulCUDAILi32EEvPfS0_S0_ii
  Memory accesses: 0
Kernel Launch: _Z13MatrixMulCUDAILi32EEvPfS0_S0_ii
  Memory accesses: 0
 .....................
Kernel Launch: _Z13MatrixMulCUDAILi32EEvPfS0_S0_ii
  Memory accesses: 0
Checking computed result for correctness: Result = PASS

NOTE: The CUDA Samples are not meant for performancemeasurements. Results may vary when GPU Boost is enabled.

**Comment by FlagZhao** [comment]
Solved： Add 87 to SMS as target.

**Comment by achartier** [comment]
Fixed with commit 812cd249b0fe0049b63492cc7ddc65d001d88ab3
