### ISSUE TITLE
Compute Sanitizer on Jetson Orin platform

### ISSUE THREAD

**Issue by FlagZhao** [NVIDIA/compute-sanitizer-samples#16]
Issue Description
We had a profiling tool based on sanitizer APIs working well on dedicate GPUs with X86 CPU. when we tried to migrate our profiling tool to NVIDIA Orin platform, a weird error occurs. The error is `function sanitizerMemcpyDeviceToHost failed with error The current operation cannot be performed`. We have upgraded our jetpack to the latest version and the CUDA version is 11.8 on Orin.
[This example code] contains the minimal codes to reproduce this issue. We designed a function `memcpy_debug` to use a global stream handle with highest priority to perform a memcpy from device to host. This function works well but for SANITIZER_CB_DOMAIN_MEMCPY domain. The error is from [testdriver.c:262](https://github.com/FlagZhao/testdriver/blob/0b470576222628cc60892a62e8ab8ec171d2ca1b/src/testdriver.c#L262). This example code can work on a dedicate GPU A5000 with x86 CPU.
Could you please help us to figure out what's wrong with this issue? Thanks a lot. The link is attached.

https://github.com/FlagZhao/testdriver.git

**Comment by achartier** [comment]
Hi,

Taking a first look at the code, I would advise to create the global_priority_stream at context creation time. Creating it upon first need in the memcpy callback can lead to deadlocks within the CUDA driver.

`      case SANITIZER_CBID_RESOURCE_CONTEXT_CREATION_FINISHED:
          Sanitizer_ResourceContextData *cd = (Sanitizer_ResourceContextData *)cbdata;
          sanitizer_global_priority_stream_init(cd->context);
          break;
`

This is not enough to fix the issue you reported unfortunately, so I will continue investigating. I also get a different error with CUDA 12.0:

`Sanitizer-> Sanitizer result error: function sanitizerMemset failed with error One or more of the parameters is invalid`

**Comment by FindHao** [comment]
Hi @achartier , do you compile and run the code with CUDA 12.0 on jetson Orin? When we try to run any samples compiled with CUDA 12.0, an error occurs `error code CUDA driver version is insufficient for CUDA runtime version`.  The tegra release version is like the following.
```
$ cat /etc/nv_tegra_release 
# R35 (release), REVISION: 1.0, GCID: 31346300, BOARD: t186ref, EABI: aarch64, DATE: Thu Aug 25 18:41:45 UTC 2022
```
Does it mean the current public jetpack release doesn't officially support CUDA 12.0?

**Comment by achartier** [comment]
Hi @FindHao , I was testing on x86 not Orin.

I found the following issues:

- stream should be created at context creation time to avoid deadlocks (see previous comment)
- device buffer should be allocated at context creation time to avoid calling sanitizerMemset() on a NULL pointer in the MEMCPY callback
- sanitizerMemcpyDeviceToHost  requires the host buffer to be page-locked (i.e allocated via cudaMallocHost or sanitizerAllocHost) if called from a path where CUDA reduced API serialization is active.

The 3rd point is not documented properly at the moment, we will fix that.

With these 3 points addressed, the CUDA application can run to completion. See attached file for an example.
[testdriver.txt](https://github.com/NVIDIA/compute-sanitizer-samples/files/10407977/testdriver.txt)

**Comment by FindHao** [comment]
@achartier Thanks for your reply! I test your version on Orin with CUDA 11.8, and it works! (the only issue in your code is a missing `{}` for `case SANITIZER_CBID_RESOURCE_CONTEXT_CREATION_FINISHED`)

**Comment by FlagZhao** [comment]
Thanks very much for your help. That solved this issue.
