### ISSUE TITLE
Can I get the shared mem allocated size of  kernal based on sanitizerAPI

### ISSUE THREAD

**Issue by luote1996** [NVIDIA/compute-sanitizer-samples#17]
I read the sanitizerAPIguide and tried SANITIZER_CBID_RESOURCE_DEVICE_MEMORY_ALLOC but shared memory allocation cannot be logged, global memory allocation can be logged normally when I use the cudamalloc interface

**Comment by achartier** [comment]
We will investigate adding the sizes of dynamic and static shared memory at kernel launch time.

**Comment by luote1996** [comment]
> 
do you mean that there is no interface to get the size of sharedmem in the current sanitizer_patching or sanitizer_callback interface?

**Comment by achartier** [comment]
There is not at the moment.

**Comment by luote1996** [comment]
> There is not at the moment.

ok, thank you
