### ISSUE TITLE
memoryTracker sample has little bug

### ISSUE THREAD

**Issue by luote1996** [NVIDIA/compute-sanitizer-samples#18]
```[tasklist]
### Tasks
```

**Comment by luote1996** [comment]
static std::string GetMemoryRWString(uint32_t flags)
{
    if (flags & (SANITIZER_MEMORY_DEVICE_FLAG_READ | SANITIZER_MEMORY_DEVICE_FLAG_WRITE))
    {
        return "Atomic";
    }
    else if (flags & SANITIZER_MEMORY_DEVICE_FLAG_READ)
    {
        return "Read";
    }
    else if (flags & SANITIZER_MEMORY_DEVICE_FLAG_WRITE)
    {
        return "Write";
    }
    else
    {
        return "Unknown";
    }
}
-----------------------------------------------------------------
if mem access is write or read, log will print atomic

**Comment by achartier** [comment]
Thank you for the report, a fix has been pushed.
