### ISSUE TITLE
Sanitizer reports false positive on Hopper with WGMMA instructions

### ISSUE THREAD

**Issue by ThomasRaoux** [NVIDIA/compute-sanitizer-samples#19]
I apologize if this is not the right place to file this bug.

I'm running into a bug when using sanitizer on H100 with WGMMA. It looks like the sanitizer uses the wrong access size for WGMMA LHS operand coming from shared memory causing it to report incorrect error.

It looks like the tool uses the wrong size when computing the amount of memory accessed for LHS operand by the instruction `wgmma.mma_async.sync.aligned.m64n256k16.f32.f16.f16`. The instructions loads 512Bytes per warp (or 2048 Bytes across 4 warps) but the tool seem to assume it loads 2048 Bytes for each warp. The tool reports:

========= Invalid __shared__ ? of size 2048 bytes
=========     at 0x2570 in /root/code/triton/python/tutorials/03-matrix-multiplication.py:223:matmul_kernel_0d1d2d3de4de5de6de7c8de9c10de11c
=========     by thread (224,0,0) in block (4,0,0)
=========     Address 0x1bc20 is out of bounds
while 114688 Bytes of shared memory is allocated and base address is 0x400 so this thread should read [0x1bc20-0x1BE20[ and inbound should have the range [0x400-0x1C000[ but the tool incorrectly thinks this instruction reads 2048 Bytes.

The bug can be reproduced with this branch of triton project:
https://github.com/openai/triton/tree/repro_sanitizer_bug

by doing:
git clone https://github.com/openai/triton.git
git checkout origin/repro_sanitizer_bug
cd triton/python
pip install .
compute-sanitizer python tutorials/03-matrix-multiplication.py

**Comment by Jokeren** [comment]
@achartier Could you please take a look?

In addition, I don't get the `?` symbol in `Invalid shared ?`

**Comment by Jokeren** [comment]
@ThomasRaoux Could you also provide with the version of compute-sanitizer you are using?

**Comment by ThomasRaoux** [comment]
ah yes sorry I forgot to mention it. I'm using this version:
```
NVIDIA (R) Compute Sanitizer
Copyright (c) 2020-2023 NVIDIA Corporation
Version 2023.2.2.0 (build 33191640) (public-release)
```

**Comment by achartier** [comment]
Opened bug 4311674 to track the issue internally. I will also update here once I have more news.

The ? indicates the tool is unable to assess if the detected access is a read or write.

**Comment by Jokeren** [comment]
Thank you!

**Comment by achartier** [comment]
How should I install Pytorch for this setup?

I tried installing it using pip and got a warning it wasn't compatible with the Triton version.
`torch 2.0.1 requires triton==2.0.0; platform_system == "Linux" and platform_machine == "x86_64", but you have triton 2.1.0 which is incompatible.`

It looks like the version installed does not support Hopper
`NVIDIA H100 80GB HBM3 with CUDA capability sm_90 is not compatible with the current PyTorch installation.`

**Comment by ThomasRaoux** [comment]
> How should I install Pytorch for this setup?
> 
> I tried installing it using pip and got a warning it wasn't compatible with the Triton version. `torch 2.0.1 requires triton==2.0.0; platform_system == "Linux" and platform_machine == "x86_64", but you have triton 2.1.0 which is incompatible.`
> 
> It looks like the version installed does not support Hopper `NVIDIA H100 80GB HBM3 with CUDA capability sm_90 is not compatible with the current PyTorch installation.`

I usually install nightly torch from `INSTALL PYTORCH` from the link below and pick CUDA 12.1:
https://pytorch.org/

The command line for me is:
`pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu121`

**Comment by achartier** [comment]
Thanks, I managed to get a local repro.

The issue for the ? has been root caused and will have a fix in a future version of the tool.

The shared memory size reported by the driver for the failing kernel launch is 50716 so the valid range would be [0 - 0xc61c[. It sounds like this is not the range you are expecting?

**Comment by ThomasRaoux** [comment]
> Thanks, I managed to get a local repro.
> 
> The issue for the ? has been root caused and will have a fix in a future version of the tool.
> 
> The shared memory size reported by the driver for the failing kernel launch is 50716 so the valid range would be [0 - 0xc61c[. It sounds like this is not the range you are expecting?

Maybe it is failing on a different kernel now. Do you see the out of bound error?
Sorry I should have fixed the kernel size by default it would try a few but I thought it would error on the first one.
I pushed a new commit to avoid having multiple kernels:
https://github.com/openai/triton/commit/5fce593120557b9c0808c87765264ccc5409cf67

You should see only one kernel with the matching shared memory size.

**Comment by achartier** [comment]
This is what I have now:
`========= Invalid __shared__ read of size 2048 bytes
=========     at matmul_kernel_0d1d2d3de4de5de6de7c8de9c10de11c+0x2570 in /work/triton/python/tutorials/03-matrix-multiplication.py:223
=========     by thread (224,0,0) in block (0,0,0)
=========     Address 0x1bc20 is out of bounds
`

The full shared memory size is now 0x1c400. The access at the given address spans [0x1b20-0x1c420[ so the error is expected.

Arguably, only the last warp of a group should report the faulty access, but the tool doesn't have an easy way to differentiate between the 4 warps, so they all end up reporting the error.

**Comment by ThomasRaoux** [comment]
> This is what I have now: `========= Invalid __shared__ read of size 2048 bytes ========= at matmul_kernel_0d1d2d3de4de5de6de7c8de9c10de11c+0x2570 in /work/triton/python/tutorials/03-matrix-multiplication.py:223 ========= by thread (224,0,0) in block (0,0,0) ========= Address 0x1bc20 is out of bounds `
> 
> The full shared memory size is now 0x1c400. The access at the given address spans [0x1b20-0x1c420[ so the error is expected.
> 
> Arguably, only the last warp of a group should report the faulty access, but the tool doesn't have an easy way to differentiate between the 4 warps, so they all end up reporting the error.

Each warp has its own address for LHS operand and each one loads 512 Bytes so the range accessed should be [0x1bc20-0x1be20[

The other warps 4, 5, 6 have different addresses.

**Comment by ThomasRaoux** [comment]
maybe I misunderstood how wgmma worked, hopefully @goostavz can clarify what is the expected HW behavior.

**Comment by achartier** [comment]
I have requested clarification from other Nvidia engineers and will update this issue once I have an answer.

**Comment by ThomasRaoux** [comment]
> I have requested clarification from other Nvidia engineers and will update this issue once I have an answer.

Thanks!

**Comment by achartier** [comment]
I have confirmation that the 4 warps need to point to the same memory descriptor (or different descriptors but with the same content). So all warps should have the same input address.

The documentation will be updated to be more explicit.

**Comment by ThomasRaoux** [comment]
Ok this works now. Sorry for the noise. It looks like HW only reads the value from the first warp of the group which is probably why things were working. This is great that it caught this bug in our code.

Thank you!
