### ISSUE TITLE
Mapping PCs to instructions

### ISSUE THREAD

**Issue by Jokeren** [NVIDIA/compute-sanitizer-samples#2]
`( *SanitizerCallbackBlockExit )( void*  userdata,  uint64_t pc ) `

In patching API, the official document describes PC as "the program counter of the patched instruction". When I dumped a log, I found PCs refer to the addresses of the instructions in the **memory** rather than the real offsets to the first instruction of a function. 

Do you guys have any way to find out instructions with PCs given by patching API? @achartier, @Isshaku

**Comment by Jokeren** [comment]
I would recommend adding a pc argument in `SanitizerCallbackBlockEnter` patch.

**Comment by achartier** [comment]
> I would recommend adding a pc argument in SanitizerCallbackBlockEnter patch.

That can be added, but it will only give you the entry PC of a \_\_global\_\_ function.

Would an API returning the entry PC and size of a device function (either \_\_global\_\_ or \_\_device\_\_) help here?

**Comment by Jokeren** [comment]
Thanks for your reply!

> Would an API returning the entry PC and size of a device function (either __global__ or __device__) help here?

Yes, that would be helpful. If the entry PC of a function is known, we could calculate the PC offset and look up the corresponding instruction.

**Comment by achartier** [comment]
I filed out stories for both features (add PC argument to SanitizerCallbackBlockEnter and the new API). They will be included in a future CUDA release.

**Comment by Jokeren** [comment]
Thanks! May I ask when the next version will be released?

**Comment by achartier** [comment]
I'm afraid there is no date set for this release as of today. I will update you once I have more information.

**Comment by achartier** [comment]
The APIs are now available as of CUDA 11.4, closing.
