### ISSUE TITLE
A bug in sanitizer api

### ISSUE THREAD

**Issue by Lin-Mao** [NVIDIA/compute-sanitizer-samples#21]
Hi,

I found `Sanitizer_ResourceMemoryData::flags == 0x6` rather than `0x2` if the allocation is managed memory, my cuda version 12.1.

**Comment by Lin-Mao** [comment]
Hi @achartier , I've created a repository to reproduce the bug with the callback for cudaMallocManaged. Could you please check it out?
https://github.com/Lin-Mao/sanitizer-api-bug

**Comment by achartier** [comment]
Assigning to @aladram

**Comment by Lin-Mao** [comment]
Hi @aladram @achartier, I am wondering if there's any update about this bug.

**Comment by aladram** [comment]
Thank you Lin for the ping, this is expected as these flags are not mutually exclusive. 0x6 means both 0x2 and 0x4, i.e. both `SANITIZER_MEMORY_FLAG_MANAGED` and `SANITIZER_MEMORY_FLAG_HOST_MAPPED`. If you want to check if an allocation is managed, you can check for the flag using a binary AND, see example below:
```cpp
bool isAllocationManaged = flags & SANITIZER_MEMORY_FLAG_MANAGED;
```
Please let me know if you have any additional questions, marking as closed for now,
