### ISSUE TITLE
SANITIZER_CBID_RESOURCE_STREAM_CREATED is placed before a stream has been fully created

### ISSUE THREAD

**Issue by Jokeren** [NVIDIA/compute-sanitizer-samples#3]
Here is the link to my test program.

https://github.com/Jokeren/hpctoolkit-gpu-samples/blob/master/cu_vec_add/main.cu#L45

Note the context creation routine is here:

https://github.com/Jokeren/hpctoolkit-gpu-samples/blob/master/utils/common.h#L49

In this case, I found in the callback of `cuCtxCreate`, the SANITIZER_CBID_RESOURCE_STREAM_CREATED callback is called before the SANITIZER_CBID_RESOURCE_CONTEXT_CREATION_FINISHED callback. And in the SANITIZER_CBID_RESOURCE_STREAM_CREATED callback, context and stream in cbdata point to unreasonable values. Does it seem to be an issue? I assume that in the SANITIZER_CBID_RESOURCE_STREAM_CREATED callback, we can get valid context and stream information. Please correct me if I am wrong.

**Comment by Jokeren** [comment]
@achartier Thanks!

**Comment by achartier** [comment]
Is the stream creation callback for the NULL stream (stream value is 0)?

In the next release, the API will no longer report the NULL stream creation due to the issues you are seeing.

**Comment by Jokeren** [comment]
Yes, it is creating the default NULL stream. Thanks.
