### ISSUE TITLE
Using conditions in SanitizerCallbackBlockEnter and SanitizerCallbackBlockExit callbacks

### ISSUE THREAD

**Issue by Jokeren** [NVIDIA/compute-sanitizer-samples#4]
I started with a strange problem of using spin locks in `SanitizerCallbackBlockEnter` callback.

Suppose we have the following code in `SanitizerCallbackBlockEnter` callback.

```
if (threadIdx.x == 0) {
	while (atomicCAS(lock, 0, 1));
}
__syncthreads();

output[threadIdx.x] = threadIdx.x;
```

It does not execute as I expect as nothing but thread 0 will store its id to the output buffer. However, if I insert the above code in `SanitizerCallbackMemoryAccess` callback, everything is just fine. At first, I thought it might be something wrong with my spin lock implementation. I tried to changed atomicCAS to a normal assignment like `*lock = 1` as I only have one block in my test but it still does not work.

Also, the same problem was found in `SanitizerCallbackBlockExit` callback. Moreover, using `__syncthreads` in  `SanitizerCallbackBlockExit` callback leads to dead lock.

I am wondering if there are some restrictions in using conditions in block exit and block enter callbacks?

@achartier

**Comment by Jokeren** [comment]
I can write a small test case for you guys if you need.

Thanks!

**Comment by achartier** [comment]
Sorry, I haven't been able to take a look so far. Probably next week. Can I ask on what GPU you found the issue?

**Comment by Jokeren** [comment]
Thank you for your reply!

I am working on Summit where each compute node has six Volta V100 GPUs. Our local workstation also has a V100.
