### ISSUE TITLE
Documentation error and lack of gridDim_z

### ISSUE THREAD

**Issue by Jokeren** [NVIDIA/compute-sanitizer-samples#5]
There are a few data fields have not been fully commented, such as sanitizer_callback.h Line 614-617, which causes bad online documentation.

https://docs.nvidia.com/cuda/sanitizer-docs/SanitizerApi/annotated.html#structSanitizer__LaunchData

```
 614     uint32_t gridDim_y;                                                                                                                                 
 615     uint32_t blockDim_x;
 616     uint32_t blockDim_y;
 617     uint32_t blockDim_z;
```
Besides, I think `gridDim_z` property is missing here, or there is a reason to not record it? Though we do not use it often.

**Comment by achartier** [comment]
Thanks for reporting these issues.

The next release will include gridDim_z and the documentation will be fixed.
