### ISSUE TITLE
Is sanitizer available on ppc64le?

### ISSUE THREAD

**Issue by Jokeren** [NVIDIA/compute-sanitizer-samples#6]
I would like to try sanitizer on ppc64le platforms but didn't find the library in CUDA directory. Is there a plan to make sanitizer available on ppc64le?

**Comment by achartier** [comment]
We are currently working on it, ppc64le will be the next platform with support added to the sanitizer.

**Comment by achartier** [comment]
The ppc64le version is now released as part of the CUDA toolkit, closing.
