### ISSUE TITLE
Failed to get memory access records

### ISSUE THREAD

**Issue by Jokeren** [NVIDIA/compute-sanitizer-samples#8]
Hi, @achartier, I found a weird problem. 

```
__global__
void vecAdd(int *l, int *r, int *p, size_t N, size_t iter) {
  size_t idx = blockDim.x * blockIdx.x + threadIdx.x;
  for (size_t i = 0; i < iter; ++i) {
    if (idx < N) {
      p[idx] += l[idx] + r[idx];
    }
  }
}
```

For this code, we are supposed to get at least some memory access records. However, with a simple instrumentor, I failed to get any of them. 

The test case is here:

https://github.com/Jokeren/sanitizer-bug-reproducer/blob/master/run_cuda_vec_add.sh

In the block enter callback, I used a atomicAdd to accumulate every thread.
In the memory access callback, I used a atomicAdd to accumulate every memory access.
With N threads, the return value is supposed to be (N / 32 * 32) + M, where M > 0. However, in the test, with 1024 threads, the return value was 1024 , which indicates M is zero. I guess this may have something to do with predicate usage.

**Comment by achartier** [comment]
Bug #7 was due to an error in sanitizer handling of the predicate, so it could be the same issue. I will sync your new test case on Monday and make sure this is also fixing it.

**Comment by Jokeren** [comment]
Alright, thanks!

**Comment by achartier** [comment]
This has been fixed since then, closing this issue.
