### ISSUE TITLE
How to use MemoryTracker

### ISSUE THREAD

**Issue by FindHao** [NVIDIA/compute-sanitizer-samples#9]
Hi, 
I try to make MemoryTracker working by following steps:

1. Upgrade cuda toolkit to 10.1 and fix the permission problem with https://developer.nvidia.com/nvidia-development-tools-solutions-ERR_NVGPUCTRPERM-permission-issue-performance-counters
2. Compile MemoryTracker and get the libMemoryTracker.so and MemoryTrackerPatches.fatbin.
3. Use sdk example/0_simple/matrixMul as my test application. Copy  libMemoryTracker.so and MemoryTrackerPatches.fatbin into matrixMul floder.

Method 1
4. Append `-L. -lMemoryTracker` to LIB flag and append `-I/usr/local/cuda/extras/Sanitizer/include` to INCLUDE flag in matrixMul's Makefile.
5. make && run
Method 2
6. `export LD_PRELOAD=$LD_PRELOAD:~/compute-sanitizer-samples-master/MemoryTracker/libMemoryTracker.so:/usr/local/cuda/extras/Sanitizer/libsanitizer-public.so` without modifying makefile.
7. run

Method 2 works on GTX 950 with some output but there are no memory tracking output on  GTX 1060, 1080Ti, 2060. By the way, matrixMul has some output but vectoradd has no output.
Method 1 doesn't works on any devices mentioned above.

 Could you tell me what's the problem in above steps and what should I do?

**Comment by achartier** [comment]
For method 2, I would suggest to only have `libMemoryTracker.so` in the LD_PRELOAD environment variable and to use LD_LIBRARY_PATH to specify the path to the sanitizer library.

`export LD_PRELOAD=~/github/compute-sanitizer-samples/MemoryTracker/libMemoryTracker.so
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/extras/Sanitizer/`

Also, make sure that `MemoryTrackerPatches.fatbin` is present in the current directory (or update the sample code for its expected location).

Let me know if this setup works for you.

**Comment by FindHao** [comment]
@achartier Thanks for your reply. It works on matrixMul in 1080Ti but failed in vectorAdd. I believe the reason is same with #8 .
